export enum DiaSemana {
  SEGUNDA = 'SEGUNDA',
  TERCA = 'TERCA',
  QUARTA = 'QUARTA',
  QUINTA = 'QUINTA',
  SEXTA = 'SEXTA',
  SABADO = 'SABADO',
  DOMINGO = 'DOMINGO',
}

export enum UsuarioSetor {
  FINANCEIRO = 'FINANCEIRO',
  COMERCIAL = 'COMERCIAL',
  SUPORTE = 'SUPORTE',
  DESENVOLVIMENTO = 'DESENVOLVIMENTO',
  RECURSOS_HUMANOS = 'RECURSOS_HUMANOS',
  MASTER = 'MASTER',
}

export enum TipoUnidadeNegocio {
  MATRIZ = 'MATRIZ',
  FILIAL = 'FILIAL',
  REVENDA = 'REVENDA',
}
