export enum UsuarioSetor {
  FINANCEIRO = 'FINANCEIRO',
  COMERCIAL = 'COMERCIAL',
  SUPORTE = 'SUPORTE',
  DESENVOLVIMENTO = 'DESENVOLVIMENTO',
  RECURSOS_HUMANOS = 'RECURSOS_HUMANOS',
  MASTER = 'MASTER',
}
